name: Frontend lint
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - dev
      - main
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      
      - name: setup nodejs env
        uses: actions/setup-node@v4 
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: frontend/package-lock.json
      
      - name: install dependencies
        working-directory: frontend
        run: npm install

      - name: run linter
        working-directory: frontend
        run: npm run lint
