name: Frontend build
on:
  workflow_dispatch:
  pull_request:
    branches:
      - dev
      - main
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: setup nodejs env
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: install dependencies
        working-directory: frontend
        run: npm i

      - name: run build
        working-directory: frontend
        run: npm run build

      - name: Move build to output directory
        run: |
          mkdir -p frontend-build
          cp -r frontend/dist/* frontend-build/
          rm -rf frontend
      
      - name: make pull-request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.PAT }}
          branch: build-temproary
          base: build
          delete-branch: true
